theme: jekyll-theme-minimal
title: Mapas Coletivos
description: Plataforma para criação de narrativas colaborativas. Ativa entre 2012 e 2020, criada pela Associação O Eco com apoio do Instituto Claro e parceria da Rede Nossa São Paulo.
show_downloads: true
google_analytics: UA-28984711-1
logo: /assets/img/mapas-coletivos_logo.svg
lang: pt_BR
twitter:
  username: mapascoletivos
image: /assets/img/mapas-coletivos_logo_social.png
seo:
  type: Organization
